allowed-duplicate-crates = [
    "bitflags",
    "toml_edit",
    "windows-sys",
    "windows-targets",
    "windows_aarch64_gnullvm",
    "windows_aarch64_msvc",
    "windows_i686_gnu",
    "windows_i686_msvc",
    "windows_x86_64_gnu",
    "windows_x86_64_gnullvm",
    "windows_x86_64_msvc",
    "winnow",
]

allowed-idents-below-min-chars = ["c", "i", "j", "n", "s", "w", "x", "y", "z"]
check-private-items = true
doc-valid-idents = [".."]
