version = "0.1"

# The available types of commits.
#
# This is a list of types (1 word) and their description, separated by one or
# more spaces.
types = [
    "build     updates the build system or build scripts",
    "chore     updates something that is not covered by any other type",
    "ci        updates the CI configuration",
    "debug     commit used for debugging purposes, not to be integrated",
    "deps      adds, updates or removes external dependencies",
    "docs      updates the documentation only",
    "env       updates the development environment",
    "feat      adds a new feature in the code",
    "fix       patches a code bug",
    "ide       updates the IDE configuration",
    "perf      enhances the performance, without adding a new feature",
    "refactor  refactors the code",
    "revert    reverts a previous commit",
    "sec       patches a security issue",
    "style     updates the style, like running clang-format or changing headers",
    "test      adds, updates or removes tests only",
    "wip       work in progress / to be rebased and squashed later",
]

# The list of valid scopes.
scopes = [
    # General scopes
    "cargo",
    "changelog",
    "contributing",
    "deb",
    "devshell",
    "direnv",
    "editorconfig",
    "flake",
    "git",
    "git-z",
    "readme",
    "rustfmt",
    "toolchain",
    "version",

    # Binary
    "main",

    # Lib
    "cli",
    "command",
    "config",
    "lib",

    # Commands
    "c:commit",
]

# The list of valid ticket prefixes.
ticket_prefixes = [""]

# The commit message template, written with the Tera [1] templating engine.
# [1] https://tera.netlify.app/
template = """
{{ type }}{% if scope %}({{ scope }}){% endif %}{% if breaking_change %}!{% endif %}: {{ description }}

# Feel free to enter a longer description here.

Refs: {{ ticket }}

{% if breaking_change %}BREAKING CHANGE: {{ breaking_change }}{% endif %}
"""
